default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  url: postgres://postgres:example@postgres:5432/postgres

development:
  <<: *default
  url: postgres://postgres:postgres@localhost:5432/postgres
  database: postgres
  username: postgres
  password: postgres

test:
  <<: *default
  url: postgres://postgres:postgres@localhost:5432/postgres
  database: postgres
  username: postgres
  password: postgres

production:
  <<: *default
  database: postgres
  username: postgres
  password: postgres